version: '3'
services:
  jwt:
    build: "./server"
    environment:
      - APP_ID="sessionid"
    ports:
      - "3000:3000"
  vue:
    build: "./frontend"
    ports:
      - "8081:8080"
    volumes:
      - vuedist:/app/dist
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/site-content:/usr/share/nginx/html
      - vuedist:/usr/share/vuedist/html/vue
    depends_on:
      - jwt
      - vue
volumes:
  vuedist: