version: '3'
services:
  jwt:
    build: "./server"
    environment:
      - APP_ID="sessionid"
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./site-content:/usr/share/nginx/html
    depends_on:
      - jwt